# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crd
  - ../rbac
  - ../manager

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: modelexpress-operator-params
    envs:
      - params.env

replacements:
  - source:
      kind: ConfigMap
      name: modelexpress-operator-params
      fieldPath: data.MODELEXPRESS_OPERATOR_IMAGE
    targets:
      - select:
          kind: Deployment
          name: modelexpress-operator
        fieldPaths:
          - spec.template.spec.containers.[name=operator].image
